### ISSUE TITLE
not working with qwik tryed some tricks to make it working but it doesnt work

### ISSUE THREAD

**Issue by realspinelle** [LeeviHalme/node-steam-openid#14]

**Comment by LeeviHalme** [comment]
Hi and thanks for submitting an issue. Please clarify with some example code and package.json.

**Comment by oliv-tree** [comment]
Should be resolved by #15 I believe

**Comment by LeeviHalme** [comment]
Relating to #13

**Comment by realspinelle** [comment]
still not working with last version 
![image](https://github.com/LeeviHalme/node-steam-openid/assets/39035551/da0aa32c-4689-4c6e-987c-3bf2ed8d234b)
![image](https://github.com/LeeviHalme/node-steam-openid/assets/39035551/834d3f72-6c50-4958-9600-50cb6fddf257)

**Comment by KICKGodz** [comment]
UPDATE!!!!! IT WORKS!!
Here is my code on how it works, pretty simple. Just a simple workaround for working with Qwik.
```js
const steam = new SteamAuth({
  realm: "URL HERE", // Site name displayed to users on logon
  returnUrl: "URL CALLBACK HERE", // Your return route
  apiKey: STEAMAPIKEY // Steam API key
});

const redirect = (request: RequestEvent, url: string) => {
    request.redirect(307, url)
    request.getWritableStream().close()
}

export const onGet: RequestHandler = async (request: RequestEvent) => {
    const redirectUrl = await steam.getRedirectUrl();
    console.log(redirectUrl)
    let req = {
        "url": request.url.href,
        "method": request.method
    }
    try {
        const user = await steam.authenticate(req);
        console.log(user)
        //...do something with the data
      } catch (error) {
        console.error(error);
      }
    request.send(200, "Testing")
};
```

While I just threw this together quickly, I added a redirect function to allow for the Redirect URI redirect as Qwik has problems with out-of-site redirects. Hope this helps.

**Comment by realspinelle** [comment]
Small problem ur not using that redirect function anywhere

**Comment by Vakiyama** [comment]
> UPDATE!!!!! IT WORKS!! Here is my code on how it works, pretty simple. Just a simple workaround for working with Qwik.
> 
> ```js
> const steam = new SteamAuth({
>   realm: "URL HERE", // Site name displayed to users on logon
>   returnUrl: "URL CALLBACK HERE", // Your return route
>   apiKey: STEAMAPIKEY // Steam API key
> });
> 
> const redirect = (request: RequestEvent, url: string) => {
>     request.redirect(307, url)
>     request.getWritableStream().close()
> }
> 
> export const onGet: RequestHandler = async (request: RequestEvent) => {
>     const redirectUrl = await steam.getRedirectUrl();
>     console.log(redirectUrl)
>     let req = {
>         "url": request.url.href,
>         "method": request.method
>     }
>     try {
>         const user = await steam.authenticate(req);
>         console.log(user)
>         //...do something with the data
>       } catch (error) {
>         console.error(error);
>       }
>     request.send(200, "Testing")
> };
> ```
> 
> While I just threw this together quickly, I added a redirect function to allow for the Redirect URI redirect as Qwik has problems with out-of-site redirects. Hope this helps.

does this not have anything to do with Qwik asking for you to throw redirect()? https://qwik.builder.io/docs/middleware/#redirect

**Comment by Vakiyama** [comment]
Hey, still stuck here.
```typescript
import { type RequestHandler } from '@builder.io/qwik-city';
import { steam } from '../../index';

export const onGet: RequestHandler = async ({ url, method, redirect }) => {
    console.log(url.searchParams, "identity");
    const expressifiedRequest = {
        "url": url.href,
        "method": method,
    };
    const user = await steam.authenticate(expressifiedRequest);
    console.log(user);
    throw redirect(308, "https://localhost:5173/");
}
```
this route is hit on redirect after my steam portal. I seem to be getting some vite error:

```shell
TypeError: Invalid value used in weak set
    at WeakSet.add (<anonymous>)
    at output ([...]/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:12851:30)
    at Object.error ([...]/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:12893:13)
    at logError ([...]/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:43797:26)
    at viteErrorMiddleware ([...]/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:43811:9)
    at call ([...]/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:50685:7)
    at next ([...]/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:50633:5)
    at [...]/node_modules/@builder.io/qwik/optimizer.cjs:2931:14
    at call ([...]/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:50685:7)
    at next ([...]/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:50633:5)
```
The stack trace isn't very helpful. My main issue here is that this package assumes I'm using express, but it should also show some interface for using http, so that the package can be used in all cases.

@KICKGodz could you maybe show a more complete working example? 
Yours seems to show a single route, my understanding is that we should have two routes; one for generating the steam url and redirecting, and another for receiving the redirect from the steam portal. I wasn't able to get a working solution following your example.

**Comment by KICKGodz** [comment]
@Vakiyama Totally, below is my full code for Steam auth:
```js
import type { RequestEvent, RequestHandler } from "@builder.io/qwik-city";
import { XMLParser } from "fast-xml-parser";
import SteamAuth from "node-steam-openid";

const groupID = "103582791474213424"

const steam = new SteamAuth({
    realm: "https://i-love.dev", // Site name displayed to users on logon
    returnUrl: "https://i-love.dev/oauth/steam", // Your return route
    apiKey: process.env["STEAM_API_KEY"] as string // Steam API key
});

const redirect = (request: RequestEvent, url: string) => {
    request.redirect(307, url)
    request.getWritableStream().close()
}

export const onGet: RequestHandler = async (request: RequestEvent) => {
    if(request.query.get("openid.claimed_id") == null) {
        const redirectUrl = await steam.getRedirectUrl();
        redirect(request, redirectUrl)
        return
    }
    let req = {
        "url": request.url.href,
        "method": request.method
    }
    try {
        const user = await steam.authenticate(req);
        let profileXML = await (await fetch(`${user.profile}?xml=1`)).text()
        const parser = new XMLParser();
        let { profile: profile } = parser.parse(profileXML);
        if(profile.groups == undefined) {
            request.send(404, "Not in Group")
            return
        }
        let inGroup = profile.groups.group.find((group: any) => group.groupID64 == groupID)
        if(inGroup == undefined) {
            request.send(404, "Not in Group")
            return
        }
        request.send(200, "In Group")
        return
    } catch (error) {
        console.error(error);
        request.send(500, "There was a server error")
        return
    }
}
```

Also should be noted that I use only 1 route instead of 2. It's fine to use either and just depends on how you want to use it. You just have to replace some of the key info with your own keys and urls.
